### ISSUE TITLE
A few issues and a question 

### ISSUE THREAD

**Issue by opsydev** [maroux/Firefly-YNAB4-Importer#1]
Hey,
Thanks for building the tool! I am trying to import my YNAB4 info for the last six years into Firefly and have been running into a few issues and am currently stuck. Python isn't my forte so have been fixing things as best I could.

Not sure if you prefer separate issues for things that I was able to fix, so listing them out here:

1. Had to install Colorama manually:
It's a dependency in code but is not part of the pip package. So in my venv I had to install it manually.

2. Accounts with no starting balance break import:
For some of my account I don't have a starting balance so the import script crashes on with
```
Traceback (most recent call last):
  File "firefly_ynab4_importer/main.py", line 1446, in <module>
    cli()
  File "/Users/raveesh/Projects/playground/ff-import/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/raveesh/Projects/playground/ff-import/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/raveesh/Projects/playground/ff-import/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/raveesh/Projects/playground/ff-import/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/raveesh/Projects/playground/ff-import/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "firefly_ynab4_importer/main.py", line 1442, in import_transactions
    importer.run(dry_run)
  File "firefly_ynab4_importer/main.py", line 638, in run
    self._process_accounts()
  File "firefly_ynab4_importer/main.py", line 795, in _process_accounts
    start_date, balance = starting_balances[acc]
KeyError: 'Tangerine MasterCard'
```

I got around this by changing line 792 to:
```
            if acc in starting_balances:
                start_date, balance = starting_balances[acc]
```

But now I'm stuck with this error:
```
Traceback (most recent call last):
  File "firefly_ynab4_importer/main.py", line 1445, in <module>
    cli()
  File "/Users/raveesh/Projects/playground/ff-import/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/raveesh/Projects/playground/ff-import/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/raveesh/Projects/playground/ff-import/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/raveesh/Projects/playground/ff-import/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/raveesh/Projects/playground/ff-import/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "firefly_ynab4_importer/main.py", line 1441, in import_transactions
    importer.run(dry_run)
  File "firefly_ynab4_importer/main.py", line 639, in run
    self._process_transactions()
  File "firefly_ynab4_importer/main.py", line 880, in _process_transactions
    assert (
AssertionError: Unable to process transaction with unknown category: |Income:Available this month|
```

I can't figure out how that is supposed to be handled. Is this something in the config I need to change? 

Thanks

**Comment by maroux** [comment]
@opsydev 

Thanks for the bug report. I've fixed the 3 issues mentioned in this ticket - please retry with `v0.3.1`.

One comment - I think your config file includes `category_field = "Category"` - which makes categories that include Category and Sub Category, like `Income:Available this month`. This is fine if you want that, but I like the default, which is `category_field = "Sub Category"` - which makes categories like `Available this month`.
